name: DeltaLogin
options:
  bundleIdPrefix: com.fake
  deploymentTarget:
    iOS: "15.0"
targets:
  DeltaLogin:
    type: application
    platform: iOS
    sources:
      - path: .
        type: group
        includes:
          - "*.swift"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        TARGETED_DEVICE_FAMILY: "1"
    info:
      path: Info.plist